# Config file for genqlient.
# genqlient generates GraphQL queries in Go files.

# See https://github.com/Khan/genqlient/blob/main/docs/genqlient.yaml

schema:
- "schema.graphql"

operations:
- "queries.graphql"

generated: generated.go

bindings:
  DateTime:
    type: time.Time
  BigInt:
    type: int
  Bytes:
    type: "[]byte"
